version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-testing}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-testing}
      - AWS_REGION=${AWS_REGION:-ca-central-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-mon-bucket-faiss}
      - COPILOT_TOKEN=${COPILOT_TOKEN}
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./output:/app/output
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s