name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TESTING: "true"
      SKIP_GIT_CALLS: "true"
      AWS_REGION: ca-central-1
      COPILOT_API_URL: https://api.githubcopilot.com/chat/completions
      COPILOT_TOKEN: your_github_token
      ENV: test
      FAISS_INDEX_FILE: index.faiss
      FAISS_METADATA_FILE: id_mapping.json
      REPO_DIR: test_repo
      REPO_URL: https://github.com/test/repo.git
      S3_BUCKET_NAME: test-bucket

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false
          poetry config virtualenvs.in-project false

      - name: Run Python Linters
        run: |
          poetry add --group dev ruff
          poetry run ruff check --exclude tests/ --output-format=github .
          poetry run ruff format --exclude tests/ --check .

      - name: Run Tests with Coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          poetry run coverage run -m pytest --junitxml=test-results.xml
          poetry run coverage xml
          poetry run coverage report
